Added Tree Traversal (preorder, inorder, post order)
saurabh47/Popular_Coding_Questions_Solution pull request #13
Opened 2020-10-09 09:10 UTC by MansiAyer

2020-10-10 08:44 UTC, saurabh47 requested changes

2020-10-10 08:44 UTC, saurabh47 commented on Binary Tree Traversal/preorder-inorder-postorder.c
> +int data;#include<stdio.h>
* Please check your code.You have added `#include<stdio.h>`.
also close properly close the `struct node`
 * Please add README.md file inside `Binary Tree Traversal` directory.write some description about algorithm & input & output sample.

2020-10-13 17:23 UTC, MansiAyer commented
Sorry for taking so long to respond, I had a few assignments from college so I was short on time. I'll update this by tomorrow afternoon!

2020-10-14 20:08 UTC, saurabh47 requested changes
Nice implementation @MansiAyer with extra search functionality.
Please rename the file `ReadMe.md` to `README.md`

2020-10-15 04:05 UTC, MansiAyer commented
Done 👍

2020-10-15 14:05 UTC, saurabh47 approved these changes

2020-10-15 14:05 UTC, merged